### ISSUE TITLE
Edit screens fatal on PHP8

### ISSUE THREAD

**Issue by rmuit** [d6lts/date#1]
For anyone just keeping up with the repo and considering updating to PHP8: this is likely to be the biggest non-Core blocker.

Patch at https://www.drupal.org/project/d6lts/issues/2004508#comment-14090564

(Also: look through https://www.drupal.org/project/issues/d6lts for more "PHP8" if interested.)

**Comment by dsnopek** [comment]
Thanks! I just committed the patch from that issue
